version: "3.1"

services:
  db:
    image: "postgres:11"
    container_name: "project_phoenix_db"
    ports:
      - "5432:5432"
    volumes:
      - ./data/adm_platform:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=developing
      - POSTGRES_PASSWORD=demosapp1!

volumes:
  adm_platform_data: